### ISSUE TITLE
iso checksum type deprecated - I used below to fix. HTH.

### ISSUE THREAD

**Issue by paulh347** [ssasso/packer-vyos-vagrant#1]
1 error occurred:
* Deprecated configuration key: 'iso_checksum_type'. Please call packer fix
against your template to update your template to be compatible with the current
version of Packer. Visit https://www.packer.io/docs/commands/fix/ for more
detail.

Update the JSON format using the command 

$ packer fix vyos.json > vyosnew.json

once this is done, generate a checksum of the iso 

$ sha256sum <isofilename.iso>

edit  the vyosnew.json file and add the line just under where the "iso_url" is specified

"iso_checksum": "<paste_checksum_here>",

The JSON file should then work with the latest version of packer.

**Comment by ssasso** [comment]
Thanks!
I updated the json file, and created a `build.sh` that calculates the checksum and automagically append it to the json file.
